# Generated by Django 6.0.5 on 2026-06-24 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="ollama", max_length=80)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("ollama", "Ollama"),
                            ("openrouter", "OpenRouter"),
                            ("openai_compatible", "OpenAI Compatible"),
                            ("vllm", "vLLM"),
                            ("sglang", "SGLang"),
                        ],
                        default="ollama",
                        max_length=40,
                    ),
                ),
                ("base_url", models.URLField(default="http://127.0.0.1:11434/v1")),
                ("model", models.CharField(default="gpt-oss:120b", max_length=160)),
                (
                    "api_key",
                    models.CharField(blank=True, default="ollama", max_length=500),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderHealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("checking", "Checking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="providers.providerconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
