# Generated by Django 6.0.5 on 2026-06-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningcard",
            name="next_topic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
