# Generated by Django 6.0.5 on 2026-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=240),
        ),
    ]
